# Directory structure:
# .
# ├── ansible.cfg
# ├── ec2.ini
# ├── ec2.py
# ├── playbook.yml
# └── requirements.txt

# playbook.yml
- name: Test EC2 connectivity
  hosts: tag_Name_MyEC2Instance
  gather_facts: no
  tasks:
    - name: Ping EC2 instance
      ansible.builtin.ping:
